### ISSUE TITLE
Any news? :V

### ISSUE THREAD

**Issue by Tsubasaza** [happypandax/server#17]
How's the progress so far? Can't wait to use the new version, any screenshots you could share with us while we wait?

**Comment by Pewpews** [comment]
Uhm, yes, I'll post something on my twitter soon.

It's nowhere near being done yet but atleast a usable version can soon be realized.
If you can't wait for my post, try building and see for yourself. I updated the instructions in the [docs](https://pewpews.github.io/happypandax/install.html#building).

**Comment by Pewpews** [comment]
Also, I forgot to mention that you can convert your HP database to HPX database with the script named `HPtoHPX.py`.

**Comment by Pewpews** [comment]
posted #29
