### ISSUE TITLE
Any updates on when the binary release?

### ISSUE THREAD

**Issue by YukiSakuma** [happypandax/server#38]
I get critical errors on HP often

**Comment by emmauss** [comment]
why did you edit your issue. also  this aint the issue tracker for HP.

**Comment by YukiSakuma** [comment]
I am referring to HPx binary release as I get many critical errors on HP

**Comment by emmauss** [comment]
it is currently in preview. no binary planned yet. also there is no other use for HPX now other than dev purposes, as it cant read galleries yet.

**Comment by Pewpews** [comment]
@YukiSakuma Hi, please hold on a bit longer. No ETA for release, but it's surely being worked on.

**Comment by Pewpews** [comment]
[HPX Preview has now been released](https://github.com/happypandax/server/releases/tag/v0.0.1)
