### ISSUE TITLE
Mascot

### ISSUE THREAD

**Issue by Pewpews** [happypandax/server#39]
Hi guys,
I decided to draw us a mascot but I need help. Which one do you prefer?
1:
<img src="https://user-images.githubusercontent.com/11841002/30777798-9f2f2122-a0c3-11e7-8038-05334bd5f0d7.png" width="200">
2:
<img src="https://user-images.githubusercontent.com/11841002/30777820-41183c9e-a0c4-11e7-9d0c-b2ba751c4c21.png" width="200">

**Comment by emmauss** [comment]
2

**Comment by arisune** [comment]
They're both cute but I'd say 1

**Comment by johanaxel007** [comment]
I prefer 1.

**Comment by Zuescho** [comment]
1

**Comment by xd1986k** [comment]
1

**Comment by YukiSakuma** [comment]
1

**Comment by Pewpews** [comment]
Thanks for the replies. I went with 1! :)
