### ISSUE TITLE
Bug when scrapping for artists with multiple aliases

### ISSUE THREAD

**Issue by CyanLeader** [happypandax/server#40]
I've come across a bug when scrapping for artists with multiple aliases. I'll be using the loli mangaka Molokonomi | Hiraya Nobori as an example. When scrapping a gallery, say, https://exhentai.org/g/599825/7291bc8af8/, the tags scrapped are as follows:

Artist:molokonomi, Female:[bloomers, lolicon], Language:[english, translated], Male:[coach, dilf], 

The artist field is missing the newer name.

**Comment by Pewpews** [comment]
Please use https://github.com/Pewpews/happypanda for HP related issues.
As for your issue, the EH API only returns one alias:
```
{
	"gmetadata": [
		{
			"gid": 599825,
			"token": "7291bc8af8",
			"archiver_key": "419699--d7ad52eef4a9420a8687d4eb565bb8814de59e17",
			"title": "[Molokonomi] Lolicon Kiraidesu. | I Hate Lolicon&#039;s (COMIC LO 2012-02) [English] [Kameden]",
			"title_jpn": "[MOLOKONOMI] ロリコン嫌いです。 (COMIC LO 2012年02月号) [英語]",
			"category": "Manga",
			"thumb": "https://ehgt.org/8e/6f/8e6faf9e5d6332a18493ea80ce082bf121e905c7-628272-1097-1600-jpg_l.jpg",
			"uploader": "egoplant",
			"posted": "1370570508",
			"filecount": "17",
			"filesize": 16128797,
			"expunged": false,
			"rating": "4.81",
			"torrentcount": "1",
			"tags": [
				"language:english",
				"language:translated",
				"artist:molokonomi",
				"male:coach",
				"male:dilf",
				"female:bloomers",
				"female:lolicon"
			]
		}
	]
}
```

We'd have to ask EH to return all aliases.
