### ISSUE TITLE
Make viewing images fit into web browser screen

### ISSUE THREAD

**Issue by YukiSakuma** [happypandax/server#43]
Happy new year and thanks for the release

Just like the good ole HP can you make it possible to view the images fit into screen just like viewing it in the windows photo viewer?

**Comment by YukiSakuma** [comment]
This seems to be a browser problem I've tried it with Chromium based browsers and it doesn't resize the images to fit to screen

**Comment by Pewpews** [comment]
There is a CSS property limiting the width. I,ll add more options next release.

**Comment by YukiSakuma** [comment]
Just inquiring, still not implemented? I tried the latest release just now 0.0.8 but the images won't still fit in browser

The alternative for now is using the external image viewer, I can use it in Irfan, but how to set the path if I want to use windows photo viewer?

**Comment by Pewpews** [comment]
Hello, the images should "fit" in the browser if you choose the *Fit Height* scaling option in the reader options. 
![billede](https://user-images.githubusercontent.com/11841002/36391799-10da1ace-15a0-11e8-83dc-ae672024273c.png)

Was this not what you wanted? If not, then it seems that I have misunderstood. In that case, an image to demonstrate it would be wonderful.

**Comment by YukiSakuma** [comment]
I don't have any of that here is a pic from 0.0.8
![image](https://user-images.githubusercontent.com/16185735/36427034-f4f0a070-1686-11e8-9f37-7e6c6f719d1b.png)

**Comment by Pewpews** [comment]
Sure that
