### ISSUE TITLE
Converting HP database to HPX database

### ISSUE THREAD

**Issue by celroid** [happypandax/server#46]
>: Progress: |██████████████████████████████████████████████████| 100.0%
>: Resolving gallery pages...
>: Creating gallery lists
>: Adding languages...
>: Adding artists...
>: Adding gallery types...
>: Adding gallery status...
>: Adding gallery namespaces...
>: Adding gallery tags...
>: Adding galleries...
>: Adding gallery lists...
>: Committing... (might take a while)
>: (sqlite3.IntegrityError) UNIQUE constraint failed: language.name [SQL: 'INSERT INTO language (properties, name) VALUES (?, ?)'] [parameters: ('{}', 'English')] (Background on this error at: http://sqlalche.me/e/gkpj)
None of them show up in HPX

**Comment by Pewpews** [comment]
If the HPX database already existed, delete it and try again.

**Comment by celroid** [comment]
It "worked" after following your instructions but there are still 0 galleries on the webclient.

**Comment by Pewpews** [comment]
Can you post the output of the process? Particularly the first part.

**Comment by Pewpews** [comment]
Never mind. The issue will be fixed in the next release.

**Comment by Pewpews** [comment]
Fixed in `v0.0.7`
